"""task to feedback

Revision ID: 7c8979e05723
Revises: 5960e8216d49
Create Date: 2025-05-08 22:00:22.100166

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7c8979e05723"
down_revision: Union[str, None] = "5960e8216d49"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("title", sa.String(length=50), nullable=False))
    op.add_column("tasks", sa.Column("accuracy", sa.Float(precision=3), nullable=True))
    op.add_column("tasks", sa.Column("errors", sa.JSON(), nullable=True))
    op.create_check_constraint(
        constraint_name="check_accuracy",
        table_name="tasks",
        condition="accuracy >= 0.0 AND accuracy <= 100.0",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "errors")
    op.drop_column("tasks", "accuracy")
    op.drop_column("tasks", "title")
    op.drop_constraint(
        constraint_name="check_accuracy",
        table_name="tasks",
        type_="check",
    )
    # ### end Alembic commands ###
