"""change errors to msitakes

Revision ID: c7e1b585e358
Revises: 7c8979e05723
Create Date: 2025-05-17 18:30:22.182008

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7e1b585e358"
down_revision: Union[str, None] = "7c8979e05723"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "errors", new_column_name="mistakes")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "mistakes", new_column_name="errors")
    # ### end Alembic commands ###
