"""indexes

Revision ID: d6a08a1eb0c1
Revises: defd820781f5
Create Date: 2025-04-17 22:09:34.756170

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "d6a08a1eb0c1"
down_revision: Union[str, None] = "defd820781f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("task_text_id_idx", "tasks", ["text_id"], unique=False, postgresql_using="hash")
    op.create_index("task_user_id_idx", "tasks", ["user_id"], unique=False, postgresql_using="hash")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("task_user_id_idx", table_name="tasks", postgresql_using="hash")
    op.drop_index("task_text_id_idx", table_name="tasks", postgresql_using="hash")
    # ### end Alembic commands ###
